import { Film } from "./film";

/**
 * Mock de la clase Film con las películas añadidas
 */
export const FILMS: Film[] = [
  {id: 1, age: 2011, name: 'Captain America', image: 'https://media.comicbook.com/2017/10/captain-america-the-first-avenger-movie-poster-marvel-cinematic--1038891.jpeg' , synopsis: 'Nacido durante la Gran Depresión (años 30), Steve Rogers creció como un chico enclenque en una familia pobre. Horrorizado por las noticias que llegaban de Europa sobre los nazis, decidió enrolarse en el ejército; sin embargo, debido a su precaria salud, fue rechazado una y otra vez. Enternecido por sus súplicas, el General Chester Phillips le ofreció la oportunidad de participar en un experimento especial: la "Operación Renacimiento". Tras administrarle el “Suero Super-Soldado” y bombardearlo con “vitarrayos”, el cuerpo de Steve se hace perfecto. A continuación, se sometió a un intensivo programa de entrenamiento físico y táctico. Tres meses después, le encomendaron su primera misión como Capitán América. Armado con un escudo indestructible, emprenderá la guerra contra el Mal como centinela de la libertad y líder de los Vengadores.'},
  {id: 2, age: 2016, name: 'Dr. Strange', image: 'https://i.pinimg.com/originals/bd/09/14/bd09145e691c402eaf89b0a0bb51a8be.jpg', synopsis: 'Marvel’s Doctor Strange sigue la historia del talentoso neurocirujano Doctor Stephen Strange quien, tras un trágico accidente automovilístico, debe poner a un lado su ego y aprender los secretos del mundo del misticismo y las dimensiones paralelas. Asentado en Greenwich Village en Nueva York, el Doctor Strange debe actuar como intermediario entre el mundo real y lo que aguarda más allá, utilizando un amplio rango de habilidades metafísicas y artefactos para proteger el Universo Cinematográfico de Marvel.'},
  {id: 3, age: 2017, name: 'Spider-man: Homecoming', image: 'https://i.pinimg.com/originals/3d/92/7f/3d927fa36356cb300fd16b5c1ac2e989.jpg', synopsis: 'Un joven Peter Parker, quien hizo su sensacional debut en ‘Captain America: Civil War’, comienza a experimentar su recién descubierta identidad como el superhéroe lanza-telarañas en Marvel’s Spider-Man: Homecoming. Emocionado por su experiencia vivida con los Vengadores, Peter regresa a casa, donde vive con su tía Maybelle, bajo la mirada vigilante de su nuevo mentor Anthony Stark. Peter intenta regresar a su rutina diaria normal – distraído por los pensamientos de demostrarse a sí mismo que es más que el amistoso vecino el Hombre Araña – pero cuando el Buitre emerge como nuevo villano, todo lo que Peter considera lo más importante se verá amenazado.'},
  {id: 4, age: 2015, name: 'Ant-man', image: 'https://images-na.ssl-images-amazon.com/images/I/71E9abm2ayL._AC_SL1111_.jpg', synopsis: 'Armado con la sorprendente habilidad de encogerse a escala pero incrementando la fuerza, el maestro ladrón Scott Lang debe abrazar a su héroe interior y ayudar a su mentor, el Doctor Henry Pym, a proteger el secreto que hay detrás del espectacular traje de Ant-Man de una nueva generación de amenazas crecientes. Contra lo que parecen obstáculos insalvables, Pym y Lang deben planear y ejecutar un atraco que salvará el mundo.'},
  {id: 5, age: 2008, name: 'Iron Man', image: 'https://media.comicbook.com/2017/10/iron-man-movie-poster-marvel-cinematic-universe-1038878.jpg', synopsis: 'El multimillonario fabricante de armas Tony Stark (Robert Downey Jr.) debe enfrentarse a su turbio pasado después de sufrir un accidente con una de sus armas. Equipado con una armadura de última generación tecnológica, se convierte en "El hombre de hierro", un héroe que se dedica a combatir el mal en todo el mundo.'},
  {id: 6, age: 2018, name: 'Black Panther', image: 'https://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/60037.jpg', synopsis: 'Después de los eventos de ‘Captain America: Civil War’, el rey T\'Challa regresa a su hogar, a la recluida y tecnológicamente avanzada nación africana de Wakanda, para servir como nuevo líder del país. Sin embargo, T’Challa pronto descubre que es desafiado por el trono por facciones dentro de su propio país. Cuando dos enemigos conspiran para destruir Wakanda, el héroe conocido como Pantera Negra debe formar equipo con el agente de la CIA Everett Ross y miembros de las Dora Milaje, fuerzas especiales de Wakanda, para evitar que Wakanda sea arrastrada hacia una guerra mundial.'},
  {id: 7, age: 2017, name: 'Guardians Of the Galaxy Vol. 2', image: 'https://images-na.ssl-images-amazon.com/images/I/A11Agdd1EQL._AC_SL1500_.jpg', synopsis: 'Preparando el contexto del ‘Awesome Mixtape #2′, Marvel’s Guardians of the Galaxy Vol. 2 continúa las aventuras del equipo mientras atraviesan los confines del cosmos. Los Guardianes deberán luchar para mantener unida su recién encontrada familia mientras desentrañan los secretos de la verdadera ascendencia de Peter Quill. Viejos enemigos se convierten en nuevos aliados y personajes favoritos de los fans de los cómics vendrán a la ayuda de nuestros héroes mientras el Universo Cinematográfico de Marvel continúa con su expansión.'},
  {id: 8, age: 2017, name: 'Thor: Ragnarok', image: 'https://images-na.ssl-images-amazon.com/images/I/81LHuCYlgEL._AC_SL1200_.jpg', synopsis: 'El mundo de Thor está a punto de explotar en Marvel’s Thor: Ragnarok. Su retorcido hermano, Loki, ha tomado el control de Asgard, la poderosa Hela ha resurgido para robar el trono y Thor es aprisionado en el otro lado del universo. Para escapar del cautiverio y salvar su hogar de una destrucción inminente, Thor debe ganar una competición alienígena mortal y derrotar a su viejo aliado y compañero Vengador... ¡El Increíble Hulk!'},
  {id: 9, age: 2012,name: 'The Avengers', image: 'http://1.bp.blogspot.com/-2KEzjbLlXpA/UDLSToUY69I/AAAAAAAAACY/_Dv33AZoZYA/s1600/The-Avengers-Movie.jpg', synopsis: 'El equipo de superhéroes más espectacular de todos los tiempos con iconos como Anthony Stark / Iron Man, El Increíble Hulk, Thor, Steven Rogers / Capitán América, Clinton Barton / Hawkeye y Natalia Romanoff / Black Widow. Cuando un enemigo inesperado amenaza con poner en peligro la seguridad mundial, Nicholas Fury, Director de la agencia internacional para el mantenimiento de la paz, conocida con el nombre de S.H.I.E.L.D., necesita encontrar urgentemente un equipo que salve al mundo del mayor de los desastres. Así empieza una búsqueda por todo el mundo para reclutar personal.'},
];
